# Generated by Django 5.1.5 on 2025-02-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_alter_profile_phone_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad_images')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.ad')),
            ],
        ),
    ]
