# Generated by Django 5.1.5 on 2025-03-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_contact_user_contact_reciever_contact_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_ad', to='user.ad'),
        ),
    ]
